included:                                       # 执行lint包含的路径
#    - Example/Folder                           # 指定目录
#    - Example//Folder/AppDelegate.swift        # 指定文件
    - SingPassion                               # 指定lint需包含../HCYNetRequestKit/Classes目录

excluded:                                       # 执行lint忽略的路径，优先级高于 `included`
    - Pods                                      # 忽略Pods

#disabled_rules:                                 # 执行时排除掉的规则
#    - identifier_name                           # 驼峰命名检查,between 3 and 40
#    - trailing_whitespace                       # 空行不能有空格

#force_try: warning                              # 避免使用强制try

#force_cast: warning                             # 直接强解类型 eg: NSNumber() as! Int

#type_name: warning                              # 类型名称违规 eg：类型首字母需大写

#shorthand_operator: warning                     # 推荐使用简短操作符 eg：+= ， -=， *=， /=

function_parameter_count:                       # 函数参数个数
    warning: 5
    error: 7
  
function_body_length:                           # 函数体长度 40lines - 100lines
    warning: 150
    error: 200

cyclomatic_complexity:                          # 代码复杂度,默认为10
    warning: 40
    error: 50

large_tuple:                                     # 元组成员个数:2
    warning: 5
    error: 7
    
line_length:                                    # 单行代码长度,默认error 200
    warning: 300
    error: 350

#file_length:                                    # 文件长度
#    warning: 500
#    error: 1200

type_body_length:                                # 类型体长度,200~350
    warning: 400
    error: 500
